# Generated by Django 4.1.7 on 2023-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='profile_image',
        ),
    ]
