# Generated by Django 4.1.7 on 2023-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_pharmacy_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
