# Generated by Django 4.1.7 on 2023-05-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_pharmacy_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
